services:
  flask:
    image: raissaglaucie34/my_flask_image  
    container_name: flask
    expose:
      - "5000"  # Expose Flask internally, to the others containers
    ports:
      - "5000:5000"  # Expose app to host machine on port 5000
    depends_on:
      - postgres
      - react 
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - my_network 
    command: ["sh", "-c", "sleep 20 && python app.py"]

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

  react:
    image: raissaglaucie34/my_react_image  
    container_name: react
    expose:
      - "80"  
    ports:
      - "80:80" 
    networks:
      - my_network  
    env_file:
      - /home/ubuntu/.env 

  postgres:
    image: postgres:13 
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data  
    ports:
      - "5432:5432"  
    networks:
      - my_network 
networks:
  my_network: 

volumes:
  postgres-data: 