name: Docker Image CI

on:
  workflow_dispatch:
  push:
   branches: [ "main"]
  pull_request:
   branches: [ "main" ]

jobs:

  sonar-test-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          cd flask && pip install -r requirements.txt
          python -m pip install --upgrade pip
          pip install pytest pytest-cov

      # - name: Run Tests & Generate Coverage Report
      #   run: |
      #     pytest --cov=. --cov-report=xml #since it doesn't have any tests, this line is commented.

      - name: SonarQube Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build:

    runs-on: ubuntu-latest
    needs: sonar-test-code

    steps:
    - uses: actions/checkout@v4

    - name: Set secrets as environment variables
      run: |
        echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> $GITHUB_ENV
        echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> $GITHUB_ENV

    - name: Build and push the Docker images 
      run: bash scripts/build-docker.sh #BE image and #FED image  
      env:
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init & Apply
      env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # mudar aqui
          AWS_DEFAULT_REGION: us-east-1
      run: |
        cd terraform/
        terraform init
        terraform plan -out=plan.out
        terraform apply -auto-approve