name: Infra-Delete

on:
  workflow_dispatch:
  # push:
  #  branches: [ "main" ]
 # pull_request:
#    branches: [ "main" ]

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2


      - name: Terraform Destroy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-2
        run: |
          cd terraform/
          terraform init
          terraform refresh
          terraform destroy -auto-approve